[package]
name = "rust-compressor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "compression"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]