[package]
name = "rust-compressor"
version = "0.1.0"
edition = "2021"

[lib]
name = "compressor"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]