name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Rust image
        uses: docker/build-push-action@v4
        with:
          context: ./rust-compressor
          push: true
          tags: ghcr.io/${{ github.repository }}/rust-compression:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push JavaScript image
        uses: docker/build-push-action@v4
        with:
          context: ./js-compressor
          push: true
          tags: ghcr.io/${{ github.repository }}/js-compression:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 